### ISSUE TITLE
Conclusion for this Project?

### ISSUE THREAD

**Issue by pitjow** [martinlindhe/ravel#1]
Hi 

I am looking for a full-featured Laravel like framework in GO. Could not find it so far, even three years after your experiment.

What was your experience with this experiment? Are you using GO now?

Regards,
pit

**Comment by martinlindhe** [comment]
This was just done to explore how to get something laravel-like up and running when I first came from PHP exploring Go.

Go offers great composition abilities, making it less cumbersome to put together your own solution without the need of batteries-included stuff like Laravel.
I do use go and think its a solid choice for web dev and many other kinds of programming.

**Comment by martinlindhe** [comment]
You might want to check out https://revel.github.io/

**Comment by reindert-vetter** [comment]
@martinlindhe @pitjow Yesterday [Confetti framework](http://www.confetti-framework.com/) was launched. Maybe you like that.
